services:
  bootstrap:
    build:
      context: .
      dockerfile: Dockerfile.bootstrap
    environment:
      - CONFIG_FILE=/app/config/config.json
    volumes:
      - ./config:/app/config
  node_1:
    build:
      context: .
      dockerfile: Dockerfile.node
    stdin_open: true    # equivale a -i
    tty: true           # equivale a -t
    depends_on:
      - bootstrap
    environment:
      - MY_NODE_ADDRESS=node_1:8888
  node_2:
    build:
      context: .
      dockerfile: Dockerfile.node
    stdin_open: true    # equivale a -i
    tty: true           # equivale a -t
    depends_on:
      - bootstrap
    environment:
      - MY_NODE_ADDRESS=node_2:8888
  node_3:
    build:
      context: .
      dockerfile: Dockerfile.node
    stdin_open: true    # equivale a -i
    tty: true           # equivale a -t
    depends_on:
      - bootstrap
    environment:
      - MY_NODE_ADDRESS=node_3:8888
  node_4:
    build:
      context: .
      dockerfile: Dockerfile.node
    stdin_open: true    # equivale a -i
    tty: true           # equivale a -t
    depends_on:
      - bootstrap
    environment:
      - MY_NODE_ADDRESS=node_4:8888
  node_5:
    build:
      context: .
      dockerfile: Dockerfile.node
    stdin_open: true    # equivale a -i
    tty: true           # equivale a -t
    depends_on:
      - bootstrap
    environment:
      - MY_NODE_ADDRESS=node_5:8888